Fixed error in save() when you have instanceMethods functions set.
TypeError: Object function ()
{
…
} has no method 'replace'

this error happens because there isn't a check if object property is a function and each property is assumed to be a value