Update connection-manager.d.ts
Received an error in typescript that "an argument for 'opts' was not provided. This argument is not required .

src/services/notificationService/notificationService.ts:127:68 - error TS2554: Expected 1 arguments, but got 0.

127       const connection = await this.db.sequelize.connectionManager.getConnection();
                                                                       ~~~~~~~~~~~~~~~

  node_modules/sequelize/types/dialects/abstract/connection-manager.d.ts:29:17
    29   getConnection(opts: GetConnectionOptions): Promise<Connection>;
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~
    An argument for 'opts' was not provided.