Dependency postgres-array is added
In sequelize@7-alpha dont included "postgres-array" and this error ocurred:

SequelizeDatabaseError: this[#arrayParserLib].parse is not a function