fix OptimisticLockError message
`BaseError` expects to receive `message`, but the `options` object is being passed.

It leads to this:
```
SequelizeOptimisticLockError: [object Object]
```

With the fix the error looks like:
```
SequelizeOptimisticLockError: Attempting to update a stale model instance: Customers
```